TORM = main.o overlord.o minion.o overlord
CC = g++
CCFLAGS =-g -std=c++11 -I /usr/local/include/ -Wall -Wpointer-arith -Wcast-qual -Wwrite-strings

all: main.o overlord.o minion.o
	${CC} ${CCFLAGS} -o overlord main.o overlord.o minion.o 

main.o: main.cpp
	${CC} ${CCFLAGS} -c main.cpp

overlord.o: overlord.cc
	${CC} ${CCFLAGS} -c overlord.cc

minion.o: minion_unix.cc 
	${CC} ${CCFLAGS} -c minion_unix.cc -o minion.o

clean:
	rm -r ${TORM}
